data = {
  "search_criteria": {
    "q": "Владимир",
    # "hometown": "Одесса",
    "online": 1,
    # "city": 314,
  },
  "search_count": 100,
  "csv_fields": [
     "activity",
     "bdate",
     "can_access_closed",
     "can_post",
     "can_see_all_posts",
     "can_write_private_message",
     "city_id",
     "city_title",
     "country_id",
     "country_title",
     "education_form",
     "education_status",
     "faculty",
     "faculty_name",
     "first_name",
     "first_post_created",
     "graduation",
     "has_mobile",
     "home_phone",
     "id",
     "is_closed",
     "last_name",
     "last_seen_platform",
     "last_seen_time",
     "main_artists_0_domain",
     "main_artists_0_id",
     "main_artists_0_name",
     "mobile_phone",
     "nickname",
     "online",
     "online_app",
     "online_mobile",
     "photo",
     "photo_big",
     "photo_medium",
     "relation",
     "relation_partner_first_name",
     "relation_partner_id",
     "relation_partner_last_name",
     "screen_name",
     "sex",
     "status_audio_artist",
     "status_audio_date",
     "status_audio_duration",
     "status_audio_genre_id",
     "status_audio_id",
     "status_audio_is_explicit",
     "status_audio_is_hq",
     "status_audio_owner_id",
     "status_audio_short_videos_allowed",
     "status_audio_stories_allowed",
     "status_audio_stories_cover_allowed",
     "status_audio_title",
     "status_audio_url",
     "universities_0_chair",
     "universities_0_chair_name",
     "universities_0_city",
     "universities_0_country",
     "universities_0_education_form",
     "universities_0_education_status",
     "universities_0_faculty",
     "universities_0_faculty_name",
     "universities_0_graduation",
     "universities_0_id",
     "universities_0_name",
     "universities_1_chair",
     "universities_1_chair_name",
     "universities_1_city",
     "universities_1_country",
     "universities_1_education_form",
     "universities_1_education_status",
     "universities_1_faculty",
     "universities_1_faculty_name",
     "universities_1_graduation",
     "universities_1_id",
     "universities_1_name",
     "universities_2_chair",
     "universities_2_chair_name",
     "universities_2_city",
     "universities_2_country",
     "universities_2_education_form",
     "universities_2_education_status",
     "universities_2_faculty",
     "universities_2_faculty_name",
     "universities_2_graduation",
     "universities_2_id",
     "universities_2_name",
     "universities_3_chair",
     "universities_3_chair_name",
     "universities_3_city",
     "universities_3_country",
     "universities_3_education_form",
     "universities_3_education_status",
     "universities_3_faculty",
     "universities_3_faculty_name",
     "universities_3_graduation",
     "universities_3_id",
     "universities_3_name",
     "university",
     "university_name"
  ],
  "fetch_fields": "nickname, screen_name, sex, bdate, city, country, timezone, photo, photo_medium, photo_big, has_mobile, contacts, education, online, counters, relation, last_seen, activity, can_write_private_message, can_see_all_posts, can_post, universities",
  "mapping": {
    "city": {
      112: "Petrozavodsk",
      314: "Kyiv",
      5331: "Los Angeles",
      73: "Krasnoyarsk",
      37: "Vladivostok",
      22168: "Amsterdam",
      35: "Veliky Novgorod",
      1: "Moscow",
      33: "Bryansk",
      75: "Kursk",
      66: "Kirov",
      139: "Taganrog",
      270: "Podolsk",
      49: "Yekaterinburg",
      5103: "Chistopol",
      158: "Chelyabinsk",
      151: "Ufa",
      2: "Saint Petersburg",
      22: "Arkhangelsk",
      1611: "Tutaev",
      122: "Ryazan",
      106: "Orenburg",
      78: "Lipetsk",
      12923: "Sokol",
      110: "Perm",
      98: "Novorossiysk",
      88: "Naberezhnye Chelny",
      140: "Tambov",
      153: "Khabarovsk",
      600: "Balashov",
      62: "Kaluga",
      147: "Tyumen",
      11: "Severodvinsk",
      55: "Ivanovo",
      104: "Omsk",
      42: "Voronezh",
      6050: "Kyshtym",
      4644: "Zheleznogorsk",
      3700: "Volgodonsk",
      26: "Belgorod",
      186: "Tikhvin",
      108: "Orsk",
      18724: "Sofrino (poselok)",
      680: "Bugulma",
      1914764: "Tokyo",
      99: "Novosibirsk",
      59: "Joshkar-Ola",
      5067857: "Washingtonville",
      72: "Krasnodar",
      185: "Sevastopol",
      2001: "Pervouralsk",
      134: "Stavropol",
      1909874: "Tauragė",
      8162: "Lobnya",
      8515: "Neftegorsk",
      20637: "Belovodsk",
      20559: "Novoishimsky",
      6913: "Esil",
      354: "Anapa",
      7446: "Umba",
      95: "Nizhny Novgorod",
      105: "Oryol",
      123: "Samara",
      133: "Sochi",
      424: "Rubtsovsk",
      340: "Serpukhov",
      882: "Achinsk",
      146: "Tula",
      8: "Cherepovets",
      71: "Kostroma",
      1037: "Golitsyno",
      82: "Magnitogorsk",
      23: "Astrakhan",
      3644: "Nyandoma",
      5098: "Kopeysk",
      282: "Minsk",
      1483: "Feodosia",
      154: "Khanty-Mansiysk",
      1355: "Verkhnyaya Pyshma",
      899: "Berezniki",
      397: "Stupino",
      46: "Gorno-Altaysk",
      136: "Surgut"
    },
    "country":{
      1: "Russia",
      2: "Ukraine",
      9: "USA",
      139: "Netherlands",
      229: "Japan",
      13: "Lithuania",
      207: "Finland",
      4: "Kazakhstan",
      144: "Norway",
      3: "Belarus"
    }
  }
}